"""Changed some columns in User table

Revision ID: 23747a89811c
Revises: c338718b31ef
Create Date: 2025-06-07 00:48:37.980120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23747a89811c'
down_revision: Union[str, None] = 'c338718b31ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('session_created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_session_id'), 'users', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_session_id'), table_name='users')
    op.drop_column('users', 'session_created_at')
    op.drop_column('users', 'session_id')
    # ### end Alembic commands ###
