"""New versions of Tables and added column Course

Revision ID: 83ab022fb9e4
Revises: 23747a89811c
Create Date: 2025-06-07 02:11:43.524384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ab022fb9e4'
down_revision: Union[str, None] = '23747a89811c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.add_column('course_modules', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_course_modules_id'), 'course_modules', ['id'], unique=False)
    op.create_foreign_key(None, 'course_modules', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_constraint(None, 'course_modules', type_='foreignkey')
    op.drop_index(op.f('ix_course_modules_id'), table_name='course_modules')
    op.drop_column('course_modules', 'course_id')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
