"""New Lesson model

Revision ID: fcc128219691
Revises: 83ab022fb9e4
Create Date: 2025-06-07 02:22:18.558827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc128219691'
down_revision: Union[str, None] = '83ab022fb9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('video_link', sa.String(), nullable=False))
    op.add_column('lessons', sa.Column('description', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('video_cover', sa.String(), nullable=True))
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.drop_column('lessons', 'video_cover')
    op.drop_column('lessons', 'description')
    op.drop_column('lessons', 'video_link')
    # ### end Alembic commands ###
